language: php

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - DB=SQLITE

matrix:
  fast_finish: true
  include:

    - php: 5.6
      env:
       - CORE_VERSION=1.0.x-dev
       - PDO=0

    - php: 7.0
      env:
       - CORE_VERSION=1.1.x-dev
       - PDO=1

    - php: 7.1
      env:
       - CORE_VERSION=4.2.x-dev
       - PDO=0

    - php: 7.2
      env:
       - CORE_VERSION=4.3.x-dev
       - PDO=0

    - php: 7.3
      env:
       - CORE_VERSION=4.x-dev
       - PDO=1
       - PHPCS_TEST=1

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini || true
  - export PATH=~/.composer/vendor/bin:$PATH
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer dependencies
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:$CORE_VERSION
  - composer install --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile
  - if [[ $PHPCS_TEST ]]; then composer global require squizlabs/php_codesniffer:^3 --prefer-dist --no-interaction --no-progress --no-suggest -o; fi

script:
  - vendor/bin/phpunit vendor/silverstripe/framework/tests
  - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi
